[package]
name = "wefit"
version = "1.0.0"
authors = []

[addresses]
wefit="e492e1767c795cb66fa5f8d40f19a806c472bf56eecd0d03afe21c1ba8877b07"

[dev-addresses]
wefit="e492e1767c795cb66fa5f8d40f19a806c472bf56eecd0d03afe21c1ba8877b07"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-token"

[dev-dependencies]
